config/routes.rb
Sozo::Application.routes.draw do
  resources :illusts, only: [:create, :destroy]

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root 'top#index'

end

app/models/illust.rb
class Illust < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: true
  validates :name, presence: true
  validates :image, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save {
  	self.email = email.downcase
  }
  before_create :create_remember_token

  has_many :illusts, dependent: :destroy

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password

  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/illusts_controller.rb
class IllustsController < ApplicationController
  # before_action :set_illust, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user

  # GET /illusts
  # GET /illusts.json
  def index
    @illusts = Illust.all
  end

  # GET /illusts/1
  # GET /illusts/1.json
  def show
  end

  # GET /illusts/new
  def new
    @illust = Illust.new
  end

  # GET /illusts/1/edit
  def edit
  end

  # POST /illusts
  # POST /illusts.json
  def create
    @illust = current_user.illusts.build(illust_params)

    if @illust.save
      flash[:success] = "Illust created!"
      redirect_to edit_user_path(current_user)
    else
      flash[:error] = "fail to upload"
      redirect_to edit_user_path(current_user)
    end
  end

  # PATCH/PUT /illusts/1
  # PATCH/PUT /illusts/1.json
  def update
    respond_to do |format|
      if @illust.update(illust_params)
        format.html { redirect_to @illust, notice: 'Illust was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @illust.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /illusts/1
  # DELETE /illusts/1.json
  def destroy
    set_illust
    @illust.destroy
    redirect_to edit_user_path(current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_illust
      @illust = Illust.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def illust_params
      params.require(:illust).permit(:name, :user_id, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      # redirect_back_or user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination' # 誤りあり!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.all
  end

  # GET /users/1
  def show
    set_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @illusts = current_user.illusts
    @illust = current_user.illusts.build if signed_in?
  end

  def update
    # if @user.update_attributes(:name => params[:user][:name])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Before actions

    def correct_user
      set_user
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def top?
    controller.controller_name == 'top'
  end
end

app/helpers/illusts_helper.rb
module IllustsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      # store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 与えられたユーザーのGravatar (http://gravatar.com/) を返す。
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name+"(gravatar)", class: "gravatar")
  end
end

app/views/illusts/_form.html.erb
<%= form_for(@illust) do |f| %>
  <% if @illust.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@illust.errors.count, "error") %> prohibited this illust from being saved:</h2>

      <ul>
      <% @illust.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/illusts/_illust.html.erb
<% if illusts_path(illust) != "/illusts" %>
<li>
  "<%= illust.name %>"<br>
  <%= image_tag illust.image_url %><br>
  <% if signed_in? && current_user?(User.find_by(id: illust.user_id)) %>
    <%= link_to "delete", illust, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
  </li>
<% end %>

app/views/illusts/edit.html.erb
<h1>Editing illust</h1>

<%= render 'form' %>

<%= link_to 'Show', @illust %> |
<%= link_to 'Back', illusts_path %>

app/views/illusts/index.html.erb
<h1>Listing illusts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @illusts.each do |illust| %>
      <tr>
        <td><%= illust.name %></td>
        <td><%= illust.user_id %></td>
        <td><%= link_to 'Show', illust %></td>
        <td><%= link_to 'Edit', edit_illust_path(illust) %></td>
        <td><%= link_to 'Destroy', illust, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Illust', new_illust_path %>

app/views/illusts/new.html.erb
<h1>New illust</h1>

<%= render 'form' %>

<%= link_to 'Back', illusts_path %>

app/views/illusts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @illust.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @illust.user_id %>
</p>

<%= link_to 'Edit', edit_illust_path(@illust) %> |
<%= link_to 'Back', illusts_path %>

app/views/layouts/_footer.html.erb
<div class="container">
<div id="grayfooter">
    <div class="row">
		<div class="col-lg-5">
            <div style="margin:25px auto auto 70px;">
                <p id="categorytitle">カテゴリから探す</p>
                <div class="categorylist">
                <ul>
                    <li><a href="#">アート</a></li>
                    <li><a href="#">あいうおえ</a></li>
                    <li><a href="#">プロダクト</a></li>
                    <li><a href="#">ジャーナリズム</a></li>
                    <li><a href="#">写真</a></li>
                </ul>
                </div>
                <div class="categorylist">
                <ul>
                    <li><a href="#">アート</a></li>
                    <li><a href="#">あいうおえ</a></li>
                    <li><a href="#">プロダクト</a></li>
                    <li><a href="#">ジャーナリズム</a></li>
                    <li><a href="#">写真</a></li>
                </ul>
                </div>
                <div class="categorylist">
                <ul>
                    <li><a href="#">アート</a></li>
                    <li><a href="#">あいうおえ</a></li>
                    <li><a href="#">プロダクト</a></li>
                    <li><a href="#">ジャーナリズム</a></li>
                    <li><a href="#">写真</a></li>
                </ul>
                </div>
                <div class="clear"></div>
            </div>
        </div>	<!-- col5 -->
    	<div class="col-sm-4" id="snslist">

	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/ja_JP/all.js#xfbml=1";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
      <div id="sns">
        <div id="twi" style="float:left;"> <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://sozo.d-siy.com" data-text="想像を創造するサイト「sO-Zo」" data-lang="ja" data-related="paddy_waseda">ツイート</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </div>
       <div class="fb-like" data-href="http://sozo.d-siy.com" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
      </div>	<!-- sns -->
      <div class="clear"></div>

        </div>	<!-- col4 -->
    </div>	<!-- row -->

</div>	<!-- grayfooter -->
<div id="bottomfooter">
<a href="#">取引～～～～～</a>
<a href="#">ああああああ</a>
<a href="#">いうえおうおえ</a>
<a href="#">かきここかけ</a>
<a href="#">プライバシーポリシー</a>
<a href="#">お問合わせ</a>
<div style="float:left;">D＆SIY</div>
<div class="clear"></div>



</div>	<!-- bottomfooter -->

</div>	<!-- container -->

app/views/layouts/_header.html.erb
<div id="nav">
    <div class="container">
        <h1 id="logo">
            <a href="/"><img src="/img/logo.jpg" alt="sO-Zo" /></a>
        </h1>
        <div class="col-sm-1"></div>
            <ul>
                <li><a href="ill.html"><div class="menu">イラスト</div></a></li>
                <li><a href="item.html"><div class="menu">商品</div></a></li>
                <li><a href="designer.html"><div class="menu">作者</div></a></li>
                <li><a href="gathering.html"><div class="menu">ギャザリング</div></a></li>
            </ul>
        <div class="col-sm-1"></div>
        <div class="col-sm-4" style="margin-top:5px;">
            <div style="margin-top:5px;">
            <button type="button" class="btn btn-info btn-md">
              <span class="glyphicon glyphicon-search"></span>
            </button>
            <button type="button" class="btn btn-success btn-md">
              <span class="glyphicon glyphicon-user"></span>
            </button>
            <button type="button" class="btn btn-primary btn-md">
              <span class="glyphicon glyphicon-star"></span>
            </button>
            <button type="button" class="btn btn-warning btn-md">
              <span class="glyphicon glyphicon-shopping-cart"></span>
            </button>
            </div>
            <div class="well well-sm" style="margin-top:3px;">
            0 item - $0.00
            </div>  <!-- well -->
            <% if signed_in? %>
              <%= link_to "Profile", current_user %><br>
              <%= link_to "Settings", edit_user_path( current_user ) %><br>
              <%= link_to "Sign out", signout_path, method: "delete" %>
            <% else %>
              <%= link_to "Sign up", signup_path %><br>
              <%= link_to "Sign in", signin_path %>
            <% end %>
        </div>  <!-- col 4 -->
        <div class="clear"></div>
    </div>  <!-- container -->
</div>  <!-- nav -->
<div style="height:76px"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--nobanner-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>sO-Zo</title>
  <meta name="keywords" content="ｘｘｘｘｘｘｘｘｘｘｘ" />
  <meta name="description" content="ｘｘｘｘｘｘｘｘｘｘｘｘｘｘｘｘｘ" />
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <link rel="stylesheet" type="text/css" href="/css/style.css" />
    <!-- Bootstrap -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

	<link rel="stylesheet" href="/css/lightbox.css" media="screen"/>
	<script src="/js/modernizr.custom.js"></script>

    <% if !top? %>
	<link rel="stylesheet" type="text/css" href="/css/meny.css" />
	<% end %>

  <%= csrf_meta_tags %>

</head>
<body id='top'>
<% if !top? %>
<%= render 'shared/meny/content' %>
<div class='contents'>
<%= render 'shared/meny/arrow' %>
<% end %>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>
<hr>
<%= debug(params) if Rails.env.development? %>

<% if !top? %>
</div>
<!-- contents -->
<% end %>

    <script src="/js/jquery-1.10.2.min.js"></script>
	<script src="/js/lightbox-2.6.min.js"></script>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/js/bootstrap.min.js"></script>

    <% if !top? %>
    <script src="/js/meny.min.js"></script>
	<script type="text/javascript">
    	$(function() {
    		//alert('init meny');
        	var meny = Meny.create({
            	menuElement:  $('.meny')[0],
            	contentsElement:  $('.contents')[0]
//            menuElement: document.querySelector( '.meny' ),
//            contentsElement: document.querySelector( '.contents' )
        	});
    	});

	</script>
	<% end %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/meny/_arrow.html.erb
<div class="meny-arrow"></div>

app/views/shared/meny/_content.html.erb
<div class="meny">
  <h4>Contents</h4>
  <ul>
    <li><a href="#">最新のWeb技術を最適の戦略で</a></li>
    <li><a href="#">一気に変貌したWeb戦略</a></li>
    <li><a href="#">Social Media</a></li>
    <li><a href="#">Smart Phone</a></li>
    <li><a href="#">CMS</a></li>
    <li><a href="http://ardito.jp">Ardito</a></li>
    <li><a href="http://www.facebook.com/woorks">WOORKS</a></li>
    <li>controller.controller_name => <%= controller.controller_name %></li>
  </ul>

</div>
<!-- /#meny -->

app/views/top/index.html.erb
<div class="container">
	<div id="mainvisual">
    	<img src="./img/mainvisual.gif" alt="aaaaaa" />
    </div>	<!-- mainvisual -->

	<div class="col-sm-12 midashi">
    <p>イラスト</p>

    </div>	<!-- col12 -->

		<div class="image-row">
			<div class="image-set">

	<div class="row" id="new">
    	<div class="col-sm-3">
        	<div class="graybox">
            <p class="ribbon"><img src="./img/new_ribbon.png" alt="" /></p>
            <div class="imgarea">
            <a class="example-image-link" href="./img/example1.gif" data-lightbox="example-set" title="作品"><img class="example-image" src="./img/example1.gif" alt="" /></a>
            <div class="price">￥１００</div>
            </div>	<!-- imgarea -->
            <p class="itemtitle">作品</p>
            <p class="itemdetail">作品詳細</p>
            </div>	<!-- graybox -->
        </div>	<!-- col3 -->

    	<div class="col-sm-3">
        	<div class="graybox">
            <p class="ribbon"><img src="./img/new_ribbon.png" alt="" /></p>
            <div class="imgarea">
            <a class="example-image-link" href="./img/example1.gif" data-lightbox="example-set" title="作品"><img class="example-image" src="./img/example1.gif" alt="" /></a>
            <div class="price">￥１００</div>
            </div>	<!-- imgarea -->
            <p class="itemtitle">作品</p>
            <p class="itemdetail">作品詳細</p>
            </div>	<!-- graybox -->
        </div>	<!-- col3 -->

    	<div class="col-sm-3">
        	<div class="graybox">
            <p class="ribbon"><img src="./img/new_ribbon.png" alt="" /></p>
            <div class="imgarea">
             <a class="example-image-link" href="./img/example1.gif" data-lightbox="example-set" title="作品"><img class="example-image" src="./img/example1.gif" alt="" /></a>
            <div class="price">￥１００</div>
            </div>	<!-- imgarea -->
            <p class="itemtitle">作品</p>
            <p class="itemdetail">作品詳細</p>
            </div>	<!-- graybox -->
        </div>	<!-- col3 -->

    	<div class="col-sm-3">
        	<div class="graybox">
            <p class="ribbon"><img src="./img/new_ribbon.png" alt="" /></p>
            <div class="imgarea">
            <a class="example-image-link" href="./img/example1.gif" data-lightbox="example-set" title="作品"><img class="example-image" src="./img/example1.gif" alt="" /></a>
            <div class="price">￥１００</div>
            </div>	<!-- imgarea -->
            <p class="itemtitle">作品</p>
            <p class="itemdetail">作品詳細</p>
            </div>	<!-- graybox -->
        </div>	<!-- col3 -->
    </div>	<!-- row new -->
			</div>	<!-- image set -->
		</div>	<!-- image row -->


	<div class="col-sm-12 midashi">
    <p>商品</p>
    </div>	<!-- col12 -->

	<div class="row" id="make">
    	<div class="col-sm-4">
        	<div class="graybox">
            <div class="overflow">
            <img src="./img/example2.gif" />
            </div>	<!-- imgarea -->
            <p>クッション</p>
            </div>	<!-- graybox -->
        </div>	<!-- col4 -->

    	<div class="col-sm-4">
        	<div class="graybox">
            <div class="overflow">
            <img src="./img/example2.gif" />
            </div>	<!-- imgarea -->
            <p>クッション</p>
            </div>	<!-- graybox -->
        </div>	<!-- col4 -->

    	<div class="col-sm-4">
        	<div class="graybox">
            <div class="overflow">
            <img src="./img/example2.gif" />
            </div>	<!-- imgarea -->
            <p>スクッション</p>
            </div>	<!-- graybox -->
        </div>	<!-- col4 -->
    </div>	<!-- row make -->




	<div class="col-sm-12 midashi">
    <p>写真</p>
    </div>	<!-- col12 -->

 		<div class="image-row">
			<div class="image-set">


	<div class="row" id="new">
    	<div class="col-sm-3">
        	<div class="graybox">
            <p class="ribbon"><img src="./img/new_ribbon.png" alt="" /></p>
            <div class="imgarea">
            <a class="example-image-link" href="./img/example1.gif" data-lightbox="example-set" title="写真"><img class="example-image" src="./img/example1.gif" alt="" /></a>
            <div class="price">￥２００</div>
            </div>	<!-- imgarea -->
            <p class="itemtitle">写真</p>
            <p class="itemdetail">写真詳細</p>
            </div>	<!-- graybox -->
        </div>	<!-- col3 -->

    	<div class="col-sm-3">
        	<div class="graybox">
            <p class="ribbon"><img src="./img/new_ribbon.png" alt="" /></p>
            <div class="imgarea">
            <a class="example-image-link" href="./img/example1.gif" data-lightbox="example-set" title="写真"><img class="example-image" src="./img/example1.gif" alt="" /></a>
            <div class="price">￥２００</div>
            </div>	<!-- imgarea -->
            <p class="itemtitle">写真</p>
            <p class="itemdetail">写真詳細</p>
            </div>	<!-- graybox -->
        </div>	<!-- col3 -->

    	<div class="col-sm-3">
        	<div class="graybox">
            <p class="ribbon"><img src="./img/new_ribbon.png" alt="" /></p>
            <div class="imgarea">
            <a class="example-image-link" href="./img/example1.gif" data-lightbox="example-set" title="写真"><img class="example-image" src="./img/example1.gif" alt="" /></a>
            <div class="price">￥２００</div>
            </div>	<!-- imgarea -->
            <p class="itemtitle">写真</p>
            <p class="itemdetail">写真詳細</p>
            </div>	<!-- graybox -->
        </div>	<!-- col3 -->

    	<div class="col-sm-3">
        	<div class="graybox">
            <p class="ribbon"><img src="./img/new_ribbon.png" alt="" /></p>
            <div class="imgarea">
            <a class="example-image-link" href="./img/example1.gif" data-lightbox="example-set" title="写真"><img class="example-image" src="./img/example1.gif" alt="" /></a>
            <div class="price">￥２００</div>
            </div>	<!-- imgarea -->
            <p class="itemtitle">写真</p>
            <p class="itemdetail">写真詳細</p>
            </div>	<!-- graybox -->
        </div>	<!-- col3 -->
    </div>	<!-- row new -->
			</div>	<!-- image set -->
		</div>	<!-- image row -->



</div>	<!-- container -->


<div class="clear"></div>
<div class="container">
	<div class="row">
	    <div class="col-lg-9" id="footerbase">
        	<p><span>最新の活動報告</span><br />
COMING SOON<br />
まだ何もない</p>
        </div>	<!-- col9 -->
	    <div class="col-lg-3" id="footerleft">
            <button type="button" class="btn btn-success btn-md" style="margin:35px auto auto 130px;">
              <span>詳細はこちら</span>
            </button>
        </div>	<!-- col3 -->
	</div>	<!-- row -->

<div id="company">
	<div class="row">
    	<div class="col-lg-4">
        <div>
			<img src="./img/logo_gray.jpg" alt="" />
        </div>
        </div>	<!-- col4 -->
        <div class="col-lg-6">
        <div>
        <p id="title">About US</p>
        <p id="txt">
詳細はso-zoチームを注目してください
        </p>
        </div>
        </div>	<!-- col6 -->
    </div>	<!-- row -->
</div>	<!-- company -->

</div>  <!-- container -->

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
  <% if signed_in? && current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/index.html.erb
<div class="container">
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</ul>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<h1>Sign up</h1>
<%= link_to "Home", root_path %>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%=render'shared/error_messages'%>

      <%= f.label :name %>
      <%= f.text_field :name %><br>

      <%= f.label :email %>
      <%= f.text_field :email %><br>

      <%= f.label :password %>
      <%= f.password_field :password %><br>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %><br>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class='container'>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>
<%= @user.name %>, <%= @user.email %>
<br>
<%= link_to "Profile", user_path(@user) %>
</div>